version: 1.0.{build}
configuration: Release
build:
  project: PowerUp.EF6\PowerUp.EF6.csproj
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: L7XqLKfvL1ZaLebXHQLZtug7R8ymN2E4MAqU2m15JnwdflZBfeOfowz8DoZ+be/u