version: 1.6.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: nuget restore -PackagesDirectory ..\PowerUp\packages
build:
  project: PowerUp.sln
  verbosity: minimal
before_package:
- ps: >-
    nuget pack -Version $env:APPVEYOR_BUILD_VERSION PowerUp\PowerUp.nuspec

    nuget pack -Version $env:APPVEYOR_BUILD_VERSION PowerUp.EF6\PowerUp.EF.nuspec
artifacts:
- path: 'PowerUp*.nupkg'
deploy:
- provider: NuGet
  api_key: 
    secure: Fmxsp36aADwh2xsoMmatJ2a+k+2PNvA3qVl3LtO/D5MlhE+sgm/bgDX0p0IY20IX