version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore -PackagesDirectory ..\PowerUp\packages
build:
  project: PowerUp.sln
  verbosity: minimal
before_package:
- ps: >-
    nuget pack -Version $env:APPVEYOR_BUILD_VERSION PowerUp\PowerUp.nuspec

    nuget pack -Version $env:APPVEYOR_BUILD_VERSION PowerUp.EF6\PowerUp.EF.nuspec
artifacts:
- path: 'PowerUp*.nupkg'