version: 1.0.{build}
configuration: Release

before_build:
- cmd: nuget restore PowerUp.EF6\PowerUp.EF6.csproj -PackagesDirectory ..\PowerUp\packages

build:
  project: PowerUp.EF6\PowerUp.EF6.csproj
  verbosity: minimal

before_package:
- cmd: nuget pack -Version "$(appveyor_build_version)" PowerUp.EF6\PowerUp.EF.nuspec

artifacts:
- path: '**\PowerUp.EF*.nupkg'